# Generated by Django 4.2.19 on 2025-02-26 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
    ]
